wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.9
    start_time: 1642651857
    t:
      3:
      - 16
      4: 3.9.9
      5: 0.12.9
      8:
      - 4
      - 5
path:
  desc: null
  value: artifacts/wisdom2def_c.tsv
