# for training an idiomifier
idiomifier:
  ver: m-1-3
  desc: Just overfitting on PIE dataset, but now with <idiom> & </idiom> special tokens.
  bart: facebook/bart-base
  lr: 0.00005
  literal2idiomatic_ver: d-1-3
  idioms_ver: d-1-3
  tokenizer_ver: t-1-1
  max_epochs: 8
  batch_size: 40
  shuffle: true
  seed: 104


# for building & uploading datasets or tokenizer
literal2entities:
  ver: d-1-4
  description: The dataset for the NER approach to Idiomify.
  train_ratio: 0.8
  seed: 104
idioms:
  ver: d-1-4
  description: the set of idioms in the traning set of literal2idiomatic_d-1-4.
  literal2entities_ver: d-1-4
entities:
  ver: d-1-4
  description: The NER labels from literal2entites:d-1-4.
  idioms_ver: d-1-4

